from __future__ import annotations

import argparse
import csv
from pathlib import Path


VALID_DECISIONS = {"approved", "reference_only", "reject", "review_pass_candidate"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply decisions from a manual review batch CSV.")
    parser.add_argument("--batch", type=Path, required=True, help="Batch CSV generated by render_manual_review_batches.py")
    parser.add_argument("--review-status", type=Path, default=Path("reference_species") / "待复核" / "gbif" / "review_status.csv")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        return list(csv.DictReader(file))


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def normalize_decision(value: str) -> str:
    decision = value.strip().lower()
    aliases = {
        "approve": "approved",
        "pass": "approved",
        "ref": "reference_only",
        "reference": "reference_only",
        "reject": "reject",
        "candidate": "review_pass_candidate",
    }
    return aliases.get(decision, decision)


def main() -> int:
    args = parse_args()
    batch_rows = read_csv(args.batch)
    review_rows = read_csv(args.review_status)
    review_by_key = {
        (row.get("species", ""), row.get("filename", "")): row
        for row in review_rows
        if row.get("species") and row.get("filename")
    }

    applied = 0
    skipped = 0
    for row in batch_rows:
        decision = normalize_decision(row.get("your_decision", ""))
        if not decision:
            skipped += 1
            continue
        if decision not in VALID_DECISIONS:
            raise ValueError(f"invalid decision for item {row.get('item')}: {decision}")

        species = row["species"]
        filename = row["filename"]
        key = (species, filename)
        review = review_by_key.get(key, {"species": species, "filename": filename})
        review["status"] = decision
        review["reason"] = row.get("reason", "")
        review["note"] = f"manual_batch={args.batch.name}; item={row.get('item', '')}"
        review_by_key[key] = review
        applied += 1

    merged_rows = sorted(review_by_key.values(), key=lambda item: (item.get("species", ""), item.get("filename", "")))
    fieldnames = ["species", "filename", "status", "reason", "note"]
    for row in merged_rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)

    if not args.dry_run:
        write_csv(args.review_status, merged_rows, fieldnames)

    print(f"applied={applied} skipped={skipped} dry_run={args.dry_run}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
